# src/Kev/PlatformBundle/Resources/config/services.yml

services:
    kev_platform.antispam:
        class:     Kev\PlatformBundle\Antispam\KevAntispam
        arguments: [@mailer, %locale%, 50]
    kev_platform.doctrine.notification:
            class:     Kev\PlatformBundle\DoctrineListener\ApplicationNotification
            arguments: [@mailer]
            tags:
              - { name: doctrine.event_listener, event: postPersist }
