<?php

namespace Kev\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    /**
     * @param $limit
     * @return array
     */
    public function getLastApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('app');

        $qb->join('app.advert', 'adv')
            ->select('adv');

        $qb->orderBy('app.date', 'DESC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

}
